baseURL = "https://nikopj.github.io/"
title = "Nikola Janjušević"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

disqusShortname = ""
googleAnalytics = ""

Paginate = 10
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = "A site where I'll try to publish notes tangentially related to my research, fun with VIM and LATEX, and perhaps my ongoing struggle to become БОГОБОЈ."
title404 = "Nothing's here!"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Nikola Janjušević"
startYear = "2020"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = false #["pages"] # boolean / array of sections
hideEntryMeta = false #["pages"] # boolean / array of sections
showReadingTime = true
showLastmod = true
taxonomyCloudShuffle = true
accentColor = "#1EB100" #"#ffcd00" #"#44d62c"
hideMainMenu = true
rtl = false

[params.sidebar]
enable = true

[params.widgets]
#header = ["breadcrumbs"]
homepage = ["recent_posts"]
sidebar = ["about","sidebar_menu"]
footer = ["social_menu"]

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "|"

[params.social]
email = "npj226@nyu.edu"
github = "nikopj"
linkedin = "nikola-janjušević-554204157"

[params.comments]
enable = true

# Utterances: https://utteranc.es
[params.comments.utterances]
enable = true
issueTerm = "pathname" # pathname / url / title / og:title / <string>
label = ""
theme = "github-light"

[params.comments.utterances.github]
username = "nikopj"
repository = "nikopj.github.io"

[permalinks]
page = "/:slug/"

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1

[[menu.main]]
name = "Posts"
weight = -10
identifier = "posts"
url = "/posts/"

[[menu.main]]
name = "résumé"
weight = -10
identifier = "resume"
url = "/janjusevic_resume.pdf"

[markup]
defaultMarkdownHandler = "goldmark"
	[markup.goldmark]
		[markup.goldmark.extensions]
			definitionList = true
			footnote = true
			linkify = true
			strikethrough = true
			table = true
			taskList = true
			typographer = true
		[markup.goldmark.parser]
			attribute = true
			autoHeadingID = true
		[markup.goldmark.renderer]
			hardWraps = false
			unsafe = true
			xHTML = false
	[markup.highlight]
		codeFences = true
		guessSyntax = false
		hl_Lines = ""
		lineNoStart = 1
		lineNos = false
		lineNumbersInTable = true
		noClasses = true
		style = "monokai"
		tabWidth = 4
	[markup.tableOfContents]
		endLevel = 3
		ordered = false
		startLevel = 2
